// Server-side bridge that feeds the Approvals module (the `approvalRequests`
// collection / src/app/dashboard/approvals) from the module-specific approval
// gates that already live on Events, Tasks, Designs, Event Reports, and
// Announcements. Each of those keeps its own approval state on its own
// record (see local-data.ts's doc comments on EventItem/TaskItem's
// approvalStatus, DesignSubmissionItem.styleStatus, EventReportItem's dual
// sign-off, AnnouncementItem.status) — this module does not replace any of
// that. It fans a tracked ApprovalRequest row out to every eligible approver
// (Centre Head, Advisor, GG Campus Events Head) whenever one of those gates
// opens, so the request is visible in the Approvals inbox too, and closes
// the sibling rows out again once the underlying record is actually decided
// — whichever approver acts first on either surface resolves it everywhere.
import { readCollection, mutateCollection } from './server-db';
import { dispatchEmail, wrapInMasterEmailTemplate, findApprovalRecipients } from './email-service';
import type { ApprovalRequest } from './local-data';

type AutoApprovalEntityType = 'event' | 'task' | 'design' | 'event-report' | 'announcement';

const ENTITY_LABELS: Record<AutoApprovalEntityType, string> = {
  event: 'Event',
  task: 'Task',
  design: 'Design',
  'event-report': 'Event Report',
  announcement: 'Announcement',
};

export interface ApprovalPanelMember {
  id: string;
  name: string;
  email?: string;
  label: string;
}

/**
 * Resolves the up-to-three-member panel this whole integration routes
 * through: Centre Head, Advisor, and the GG Campus Head of Events. Any one
 * of them acting is sufficient — see cascadeCloseAutoApprovals below.
 */
export async function resolveApprovalPanel(): Promise<ApprovalPanelMember[]> {
  const members = await readCollection('members');
  const recipients = findApprovalRecipients(members as any[]);
  const panel: ApprovalPanelMember[] = [];
  const seen = new Set<string>();
  const active = (members as any[]).filter(m => m.status !== 'Terminated');

  const push = (match: { name: string; email: string } | undefined, label: string) => {
    if (!match) return;
    const member = active.find(m => m.email === match.email) || { id: match.email, name: match.name, email: match.email };
    if (seen.has(member.id)) return;
    seen.add(member.id);
    panel.push({ id: member.id, name: member.name, email: member.email, label });
  };

  push(recipients.centreHead, 'Centre Head');
  push(recipients.advisor, 'Advisor');
  push(recipients.eventsHeadGg, 'GG Campus Events Head');

  return panel;
}

export interface FanOutOptions {
  entityType: AutoApprovalEntityType;
  entityId: string;
  entityTitle: string;
  eventId?: string;
  requesterId: string;
  requesterName: string;
  requesterEmail?: string;
  message?: string;
}

/**
 * Creates one ApprovalRequest per panel member, all addressed at the same
 * underlying entity. Idempotent — a second call while a fan-out for this
 * exact entity is already pending is a no-op, so re-saving a still-pending
 * record doesn't spam duplicate rows/emails.
 */
export async function fanOutAutoApproval(opts: FanOutOptions): Promise<ApprovalRequest[]> {
  const panel = await resolveApprovalPanel();
  if (panel.length === 0) return [];

  const now = new Date().toISOString();
  let createdRows: ApprovalRequest[] = [];

  await mutateCollection('approvalRequests', (current) => {
    const alreadyPending = (current || []).some(
      (r: any) => r.entityType === opts.entityType && r.entityId === opts.entityId && r.status === 'pending' && r.autoGenerated
    );
    if (alreadyPending) return current;

    createdRows = panel.map((p, i) => ({
      id: `appr_${opts.entityType}_${opts.entityId}_${p.id}_${Date.now()}_${i}`,
      entityType: opts.entityType,
      entityId: opts.entityId,
      entityTitle: opts.entityTitle,
      eventId: opts.eventId,
      requesterId: opts.requesterId,
      requesterName: opts.requesterName,
      requesterEmail: opts.requesterEmail,
      targetMemberId: p.id,
      targetMemberName: p.name,
      targetMemberEmail: p.email,
      message: opts.message,
      status: 'pending' as const,
      createdAt: now,
      autoGenerated: true,
      approverLabel: p.label,
    }));

    return [...createdRows, ...(current || [])];
  });

  for (const row of createdRows) {
    if (!row.targetMemberEmail) continue;
    try {
      const entityLabel = ENTITY_LABELS[opts.entityType];
      const bodyHtml = `
        <p>Hello ${row.targetMemberName || 'there'},</p>
        <p>A new ${entityLabel.toLowerCase()} needs your sign-off as ${row.approverLabel}:</p>
        <p style="font-weight: 700; font-size: 15px; color: #0f172a;">${row.entityTitle}</p>
        ${row.message ? `<p style="background: #f8fafc; border-left: 3px solid #38bdf8; padding: 10px 14px; border-radius: 4px; color: #475569;">"${row.message}"</p>` : ''}
        <p>Please sign in to the LEADS Dashboard and visit <strong>Approvals</strong> to approve or reject this request.</p>
      `;
      await dispatchEmail({
        to: row.targetMemberEmail,
        subject: `Approval requested: ${row.entityTitle}`,
        bodyText: `${entityLabel} "${row.entityTitle}" needs your sign-off as ${row.approverLabel}. Sign in to the LEADS Dashboard's Approvals page to respond.`,
        bodyHtml: wrapInMasterEmailTemplate({
          pageTitle: `Approval requested: ${row.entityTitle}`,
          headerTitle: 'Approval Requested',
          headerSubtitle: `${entityLabel} sign-off needed`,
          badgeText: 'ACTION NEEDED',
          badgeColor: '#d97706',
          bodyContentHtml: bodyHtml,
        }),
        badgeText: 'ACTION NEEDED',
        badgeColor: '#d97706',
        category: 'APPROVAL_REQUEST',
      });
    } catch (emailErr) {
      console.error('[approval-sync] Failed to send fan-out notification email:', emailErr);
    }
  }

  return createdRows;
}

/**
 * Once the underlying record (Event/Task/Design/Event Report/Announcement)
 * is actually decided — by whichever approver acted, on whichever surface —
 * resolve every still-pending auto-generated ApprovalRequest row for that
 * entity so the Approvals inbox doesn't keep asking the other two panel
 * members for a sign-off that already happened.
 */
export async function cascadeCloseAutoApprovals(
  entityType: AutoApprovalEntityType,
  entityId: string,
  decision: 'approved' | 'rejected',
  decidedByName?: string
): Promise<void> {
  await mutateCollection('approvalRequests', (current) => {
    let changed = false;
    const next = (current || []).map((r: any) => {
      if (r.entityType === entityType && r.entityId === entityId && r.status === 'pending' && r.autoGenerated) {
        changed = true;
        return {
          ...r,
          status: decision,
          decidedAt: new Date().toISOString(),
          decisionNote: decidedByName ? `Resolved directly on the ${ENTITY_LABELS[entityType]} record by ${decidedByName}.` : `Resolved directly on the ${ENTITY_LABELS[entityType]} record.`,
        };
      }
      return r;
    });
    return changed ? next : current;
  });
}
