export interface BoardMember {
  id: string;
  placeholderId?: number;
  name: string;
  role: string;
  designation: string;
  roleGroup:
    | "Centers Leadership"
    | "Alumni Student Council"
    | "Student Core Council"
    | "Student Advisory Council"
    | "Student Trainee Associates"
    | "Governing & Advisory";
  initials: string;
  image?: string;
  bio?: string;
  message?: string;
  affiliation: string;
  linkedin?: string | null;
}

export const LEADERSHIP_MESSAGES: BoardMember[] = [
  {
    id: "kuldeep-raina",
    placeholderId: 1,
    name: "Prof. Kuldeep Kumar Raina",
    role: "PATRON",
    designation: "Hon. Vice Chancellor, RUAS",
    roleGroup: "Centers Leadership",
    initials: "KR",
    image: "/images/leadership/kuldeep-raina.webp",
    message:
      "Developing futuristic leaders focused on sustainable action. Leadership is responsibility, empathy, and compassion in driving India's socio-economic advancement.",
    bio: "Guiding the academic vision and strategic national direction of LEADS Next Gen Centre as Patron and Vice-Chancellor of MSRUAS.",
    affiliation: "Ramaiah University of Applied Sciences",
    linkedin: "https://www.linkedin.com/in/dr-kuldeep-raina-b4207524",
  },
  {
    id: "sharath-kumar",
    placeholderId: 2,
    name: "Dr. K. M. Sharath Kumar",
    role: "CHIEF ADVISOR",
    designation: "Dean, Faculty of Management and Commerce - RUAS",
    roleGroup: "Centers Leadership",
    initials: "SK",
    image: "/images/leadership/sharath-kumar.webp",
    message:
      "A platform for students, faculty, and industry leaders to tackle contemporary challenges and work towards Viksit Bharat 2047 through non-technical skill upliftment.",
    bio: "Dean of the Faculty of Management and Commerce, overseeing curriculum modernization and institutional industry bridges.",
    affiliation: "Faculty of Management and Commerce, RUAS",
    linkedin: "https://www.linkedin.com/in/dr-k-m-sharath-kumar-ph-d-80400714",
  },
  {
    id: "subhadeep-mukherjee",
    placeholderId: 3,
    name: "Dr. Subhadeep Mukherjee",
    role: "ADVISOR",
    designation: "CEO of Ramaiah Technology Business Incubator",
    roleGroup: "Centers Leadership",
    initials: "SM",
    image: "/images/leadership/subhadeep-mukherjee.webp",
    message:
      "We unite industry leaders and young change-makers to discuss innovative solutions, emphasizing dialogue, collaborative execution, and ethical leadership.",
    bio: "Chief Executive Officer of Ramaiah Technology Business Incubator (RTBI), guiding technology acceleration, strategic incubation, and enterprise innovation.",
    affiliation: "Ramaiah Technology Business Incubator (RTBI) / RUAS",
    linkedin: "https://www.linkedin.com/in/dr-subhadeep-mukherjee-aa78a182",
  },
];

export const EXECUTIVE_COUNCIL: BoardMember[] = [
  ...LEADERSHIP_MESSAGES,
  {
    id: "pallabi-mund",
    placeholderId: 4,
    name: "Dr. Pallabi Mund",
    role: "CENTRE HEAD",
    designation: "Centre Head, LEADS Next-Gen Centre",
    roleGroup: "Centers Leadership",
    initials: "PM",
    image: "/images/committee/pallabi-mund.webp",
    message:
      "Empowering students and faculty to build transformational leadership initiatives across campuses.",
    bio: "Centre Head of LEADS Next Gen Centre & Associate Professor at Faculty of Management and Commerce, directing day-to-day operations, multi-campus student leadership programs, and flagship summits.",
    affiliation: "LEADS Next Gen Centre / Faculty of Management and Commerce, RUAS",
    linkedin: "https://www.linkedin.com/in/dr-pallabi-mund-53163a20",
  },
  {
    id: "sujata-bijwe",
    placeholderId: 6,
    name: "Ms. Sujata Bijwe",
    role: "Head Industry Connect",
    designation: "Adjunct Faculty of Faculty of Management and Commerce, RUAS",
    roleGroup: "Centers Leadership",
    initials: "SB",
    image: "/images/committee/sujata-bijwe.webp",
    bio: "Facilitating corporate sponsorships, executive masterclasses, and national leadership board advisory partnerships.",
    affiliation: "Faculty of Management and Commerce, RUAS",
    linkedin: null,
  },
  {
    id: "ajay-r",
    placeholderId: 7,
    name: "Dr. Ajay R",
    role: "Finance Advisor & Auditor",
    designation: "Sr. Assistant Professor & Program Head - BCom, Faculty of Management and Commerce, RUAS",
    roleGroup: "Centers Leadership",
    initials: "AR",
    image: "/images/committee/ajay-r.webp",
    bio: "Managing institutional fiscal compliance, budgeting, and financial governance for all LEADS summits and workshops.",
    affiliation: "Faculty of Management and Commerce, RUAS",
    linkedin: "https://www.linkedin.com/in/ajay-r-50b467270",
  },
  {
    id: "kiran-kumar",
    placeholderId: 5,
    name: "Dr. Kiran Kumar B.M.",
    role: "Head Events (RTC Campus)",
    designation: "Associate Professor of FET, RUAS | Head - IIC, RUAS",
    roleGroup: "Centers Leadership",
    initials: "KK",
    image: "/images/committee/kiran-kumar.webp",
    bio: "Directing multi-campus operations, engineering school collaborations, and technical-to-leadership transition programs.",
    affiliation: "Faculty of Engineering & Technology, RUAS",
    linkedin: "https://www.linkedin.com/in/dr-kiran-kumar-b-m-17539769",
  },
  {
    id: "tapas-kumar-sahoo",
    placeholderId: 8,
    name: "Dr. Tapas Kumar Sahoo",
    role: "Finance Officer",
    designation: "Assistant Professor of Faculty of Management and Commerce, RUAS",
    roleGroup: "Centers Leadership",
    initials: "TS",
    image: "/images/committee/tapas-kumar-sahoo.webp",
    bio: "Academician and researcher in Commerce & Management, specializing in corporate finance, financial econometrics, and quantitative research at Faculty of Management and Commerce, RUAS.",
    affiliation: "Faculty of Management and Commerce, RUAS",
    linkedin: null,
  },
];

export const CORE_LEADERSHIP: BoardMember[] = [
  {
    id: "gurutejas-c",
    placeholderId: 8,
    name: "Mr. Gurutejas C",
    role: "Sr. President",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "GC",
    image: "/images/committee/gurutejas-c.webp",
    bio: "Spearheading overall student leadership, inter-university alliances, and strategic initiative execution.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/gurutejas-c-215216291/",
  },
  {
    id: "abhijit-arya",
    placeholderId: 9,
    name: "Mr. Abhijit Arya",
    role: "Sr. Vice President",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "AA",
    image: "/images/committee/abhijit-arya.webp",
    bio: "Overseeing summit operations, corporate delegacy integration, and national outreach initiatives.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/abhijit-arya-402570285/",
  },
  {
    id: "laksh-soorya-singh",
    placeholderId: 10,
    name: "Mr. Laksh Soorya Singh",
    role: "Sr. Events & Operations Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "LS",
    image: "/images/committee/laksh-soorya-singh.webp",
    bio: "Directing high-stakes event logistics, keynote stage production, and venue management.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/laksh-soorya-singh-ab4212291/",
  },
  {
    id: "bhawen-maroo",
    placeholderId: 11,
    name: "Mr. Bhawen Maroo",
    role: "Sr. Events & Operations Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "BM",
    image: "/images/committee/bhawen-maroo.webp",
    bio: "Managing seamless on-ground event protocol, guest hospitality, and delegate operations.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/bhawen-maroo/",
  },
  {
    id: "shreesha-sn",
    placeholderId: 12,
    name: "Ms. Shreesha S.N",
    role: "Sr. Social Media & Design Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "SS",
    image: "/images/committee/shreesha-sn.webp",
    bio: "Curating digital brand identity, multimedia storytelling, and national outreach campaigns.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/shreesha-s-n-549536292/",
  },
  {
    id: "bharvi-padia",
    placeholderId: 13,
    name: "Ms. Bharvi A Padia",
    role: "Sr. PR Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "BP",
    image: "/images/committee/bharvi-padia.webp",
    bio: "Managing press relations, national media coverage, and dignitary public affairs.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/bharvi-a-7063a62a0/",
  },
  {
    id: "arvind-rakshith",
    placeholderId: 14,
    name: "Mr. Arvind Rakshith G",
    role: "Sr. Finance & Sponsorship Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "AR",
    image: "/images/committee/arvind-rakshith.webp",
    bio: "Structuring corporate sponsorship packages, partner allocations, and financial accounting.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/arvind-rakshith-94a36a375/",
  },
  {
    id: "syed-furqaan",
    placeholderId: 15,
    name: "Mr. Syed Furqaan Ahmed",
    role: "Sr. Research & Development Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "SF",
    image: "/images/committee/syed-furqaan.webp",
    bio: "Authoring capability gap whitepapers, academic research surveys, and impact metrics.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/sydkwests/",
  },
];

export const ORGANIZING_COMMITTEE: BoardMember[] = [
  {
    id: "nuthan-h",
    placeholderId: 16,
    name: "Nuthan H",
    role: "President",
    designation: "Organizing Committee, LEADS",
    roleGroup: "Student Trainee Associates",
    initials: "NH",
    image: "/images/committee/nuthan-h.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "kunal-bhadauria",
    placeholderId: 17,
    name: "Kunal Bhadauria",
    role: "Vice President",
    designation: "Organizing Committee, LEADS",
    roleGroup: "Student Trainee Associates",
    initials: "KB",
    image: "/images/committee/kunal-bhadauria.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "kayomarz-pavri",
    placeholderId: 18,
    name: "Kayomarz Pavri",
    role: "Head - Design & Digital Media",
    designation: "Organizing Committee & Tech Lead",
    roleGroup: "Student Trainee Associates",
    initials: "KP",
    image: "/images/committee/kayomarz-pavri.webp",
    affiliation: "LEADS Next Gen Centre",
  },
  {
    id: "shwetha-s",
    placeholderId: 19,
    name: "Shwetha S",
    role: "Head - Design and Social Media",
    designation: "Organizing Committee",
    roleGroup: "Student Trainee Associates",
    initials: "SS",
    image: "/images/committee/shwetha-s.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "sudev-mitra",
    placeholderId: 20,
    name: "Sudev Mitra",
    role: "Chief Coordinator",
    designation: "Organizing Committee",
    roleGroup: "Student Trainee Associates",
    initials: "SM",
    image: "/images/committee/sudev-mitra.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "jyotsna-karn",
    placeholderId: 21,
    name: "Jyotsna Karn",
    role: "Chief Coordinator",
    designation: "Organizing Committee",
    roleGroup: "Student Trainee Associates",
    initials: "JK",
    image: "/images/committee/jyotsna-karn.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "pranav-pj",
    placeholderId: 22,
    name: "Pranav P J",
    role: "Chief Coordinator",
    designation: "Organizing Committee",
    roleGroup: "Student Trainee Associates",
    initials: "PP",
    image: "/images/committee/pranav-pj.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "shravya-t",
    placeholderId: 23,
    name: "Shravya T",
    role: "Chief Coordinator",
    designation: "Organizing Committee",
    roleGroup: "Student Trainee Associates",
    initials: "ST",
    image: "/images/committee/shravya-t.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "shriram-sg",
    placeholderId: 24,
    name: "Shriram SG",
    role: "General Secretary",
    designation: "Organizing Committee",
    roleGroup: "Student Trainee Associates",
    initials: "SS",
    image: "/images/committee/shriram-sg.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "bhavya-shree",
    placeholderId: 25,
    name: "S Bhavya Shree",
    role: "General Secretary",
    designation: "Organizing Committee",
    roleGroup: "Student Trainee Associates",
    initials: "BS",
    image: "/images/committee/bhavya-shree.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "manoj-petakamsetty",
    placeholderId: 26,
    name: "Manoj Petakamsetty",
    role: "General Secretary",
    designation: "Organizing Committee",
    roleGroup: "Student Trainee Associates",
    initials: "MP",
    image: "/images/committee/manoj-petakamsetty.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "yash-chandak",
    placeholderId: 27,
    name: "Yash Chandak",
    role: "Head - Operations and Logistics",
    designation: "Organizing Committee",
    roleGroup: "Student Trainee Associates",
    initials: "YC",
    image: "/images/committee/yash-chandak.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "niyati-chawra",
    placeholderId: 28,
    name: "Niyati Chawra",
    role: "Head - Leadership and Development",
    designation: "Organizing Committee",
    roleGroup: "Student Trainee Associates",
    initials: "NC",
    image: "/images/committee/niyati-chawra.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "sadiya-sawood",
    placeholderId: 29,
    name: "Sadiya Sawood",
    role: "Head - Leadership and Development",
    designation: "Organizing Committee",
    roleGroup: "Alumni Student Council",
    initials: "SS",
    image: "/images/committee/sadiya-sawood.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "nimisha-km",
    placeholderId: 30,
    name: "Nimisha K M",
    role: "Head - Sustainability and Innovation",
    designation: "Organizing Committee",
    roleGroup: "Alumni Student Council",
    initials: "NK",
    image: "/images/committee/nimisha-km.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "kishan-kp",
    placeholderId: 31,
    name: "Kishan KP",
    role: "Head - Marketing and Branding",
    designation: "Organizing Committee",
    roleGroup: "Student Trainee Associates",
    initials: "KK",
    image: "/images/committee/kishan-kp.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "aravind-manashetti",
    placeholderId: 32,
    name: "Aravind Manashetti",
    role: "Head - Finance and Sponsorship",
    designation: "Organizing Committee",
    roleGroup: "Student Trainee Associates",
    initials: "AM",
    image: "/images/committee/arvind-manashetti.webp",
    affiliation: "Organizing Committee",
  },
];

export const STUDENT_ADVISORY_COUNCIL: BoardMember[] = [
  {
    id: "sahana-mahadev",
    placeholderId: 33,
    name: "Sahana Mahadev",
    role: "Sr. Student Advisor",
    designation: "Student Advisory Council, LEADS",
    roleGroup: "Student Advisory Council",
    initials: "SM",
    image: "/images/committee/sahana-mahadev.webp",
    affiliation: "LEADS Student Advisory Council",
  },
  {
    id: "anurag-pandey",
    placeholderId: 34,
    name: "Anurag Pandey",
    role: "Sr. Student Advisor",
    designation: "Student Advisory Council, LEADS",
    roleGroup: "Student Advisory Council",
    initials: "AP",
    image: "/images/committee/anurag-pandey.webp",
    affiliation: "LEADS Student Advisory Council",
  },
];

export const GOVERNING_ADVISORS: BoardMember[] = [
  {
    id: "ramanan-ramanathan",
    placeholderId: 35,
    name: "Mr. Ramanan Ramanathan",
    role: "Governing Advisory Board",
    designation: "Mission Director, Atal Innovation Mission | Chairperson, DST, GoI",
    roleGroup: "Governing & Advisory",
    initials: "RR",
    image: "/images/speakers/ramanan-ramanathan.webp",
    affiliation: "Department of Science & Technology, Govt of India",
    linkedin: "https://www.linkedin.com/in/rramanan27",
  },
  {
    id: "rishikesh-patankar",
    placeholderId: 36,
    name: "Mr. Rishikesh Patankar",
    role: "Governing Advisory Board",
    designation: "Vice President, National Skill Development Corporation (NSDC)",
    roleGroup: "Governing & Advisory",
    initials: "RP",
    image: "/images/speakers/rishikesh-patankar.webp",
    affiliation: "National Skill Development Corporation",
    linkedin: "https://www.linkedin.com/in/rishikesh-patankar-ph-d-a0bb0863",
  },
  {
    id: "balakrishnan-i",
    placeholderId: 37,
    name: "Mr. Balakrishnan I",
    role: "Governing Advisory Board",
    designation: "Joint Director / Scientist, Ministry of Electronics & IT, GoI",
    roleGroup: "Governing & Advisory",
    initials: "BI",
    image: "/images/speakers/balakrisnan-i.webp",
    affiliation: "Ministry of Electronics & IT (MeitY)",
    linkedin: "https://www.linkedin.com/in/balakrishna-i-9a4257181",
  },
  {
    id: "anisshh-somani",
    placeholderId: 38,
    name: "Mr. Anisshh Somani",
    role: "Governing Advisory Board",
    designation: "Program Director, INDIAai, Govt of India",
    roleGroup: "Governing & Advisory",
    initials: "AS",
    image: "/images/speakers/ashish-somani.webp",
    affiliation: "INDIAai, Government of India",
    linkedin: "https://www.linkedin.com/in/anishsomani/",
  },
  {
    id: "vidur-dewan",
    placeholderId: 39,
    name: "Mr. Vidur Dewan",
    role: "Corporate Advisory Board",
    designation: "Associate VP, Edelman Global Advisory",
    roleGroup: "Governing & Advisory",
    initials: "VD",
    image: "/images/speakers/vidur-dewan.webp",
    affiliation: "Edelman Global Advisory",
    linkedin: "https://www.linkedin.com/in/vidur-d",
  },
  {
    id: "praveen-kamath",
    placeholderId: 40,
    name: "Dr. Praveen Kamath Kumbla",
    role: "Corporate Advisory Board",
    designation: "General Manager HR, Wipro",
    roleGroup: "Governing & Advisory",
    initials: "PK",
    image: "/images/speakers/praveen-kamath.webp",
    affiliation: "Wipro Global HR",
    linkedin: "https://www.linkedin.com/in/dr-praveen-kamath-kumbla-04111811a",
  },
];

export const BOARD_MEMBERS_DATA: BoardMember[] = [
  ...EXECUTIVE_COUNCIL,
  ...CORE_LEADERSHIP,
  ...STUDENT_ADVISORY_COUNCIL,
  ...ORGANIZING_COMMITTEE,
  ...GOVERNING_ADVISORS,
];
