export interface BoardMember {
  id: string;
  name: string;
  role: string;
  designation: string;
  roleGroup: "Patron & Executive" | "Executive Council" | "Core Committee" | "Organizing Team" | "Governing & Advisory";
  initials: string;
  image?: string;
  bio?: string;
  message?: string;
  affiliation: string;
  linkedin?: string | null;
}

export const LEADERSHIP_MESSAGES: BoardMember[] = [
  {
    id: "kuldeep-raina",
    name: "Prof. Kuldeep Kumar Raina",
    role: "Patron (LEADS Next Gen Centre)",
    designation: "Honourable Vice-Chancellor of RUAS",
    roleGroup: "Patron & Executive",
    initials: "KR",
    image: "/images/leadership/kuldeep-raina.webp",
    message:
      "Developing futuristic leaders focused on sustainable action. Leadership is responsibility, empathy, and compassion in driving India's socio-economic advancement.",
    bio: "Guiding the academic vision and strategic national direction of LEADS Next Gen Centre as the Patron and Vice-Chancellor of MSRUAS.",
    affiliation: "Ramaiah University of Applied Sciences",
    linkedin: "https://www.linkedin.com/in/dr-kuldeep-raina-b4207524",
  },
  {
    id: "sharath-kumar",
    name: "Dr. K. M. Sharath Kumar",
    role: "Chief Adviser (LEADS Next Gen Centre)",
    designation: "Professor and Dean of FMC, RUAS",
    roleGroup: "Patron & Executive",
    initials: "SK",
    image: "/images/leadership/sharath-kumar.webp",
    message:
      "A platform for students, faculty, and industry leaders to tackle contemporary challenges and work towards Viksit Bharat 2047 through non-technical skill upliftment.",
    bio: "Executive Dean of the Faculty of Management and Commerce (FMC), overseeing curriculum modernization and institutional industry bridges.",
    affiliation: "Faculty of Management and Commerce, RUAS",
    linkedin: "https://www.linkedin.com/in/dr-k-m-sharath-kumar-ph-d-80400714",
  },
  {
    id: "subhadeep-mukherjee",
    name: "Dr. Subhadeep Mukherjee",
    role: "Centre Head (LEADS Next Gen Centre)",
    designation: "Associate Professor of FMC, RUAS",
    roleGroup: "Patron & Executive",
    initials: "SM",
    image: "/images/leadership/subhadeep-mukherjee.webp",
    message:
      "We unite industry leaders and young change-makers to discuss innovative solutions, emphasizing dialogue, collaborative execution, and ethical leadership.",
    bio: "Leading daily academic operations, student leadership incubation, national summit execution, and institutional research roadmaps.",
    affiliation: "LEADS Next Gen Centre / FMC, RUAS",
    linkedin: "https://www.linkedin.com/in/dr-subhadeep-mukherjee-aa78a182",
  },
];

export const EXECUTIVE_COUNCIL: BoardMember[] = [
  ...LEADERSHIP_MESSAGES,
  {
    id: "ajay-r",
    name: "Mr. Ajay R",
    role: "Finance Head & Auditor",
    designation: "Assistant Professor of FMC, RUAS",
    roleGroup: "Executive Council",
    initials: "AR",
    image: "/images/committee/ajay-r.webp",
    bio: "Managing institutional fiscal compliance, budgeting, and financial governance for all LEADS summits and workshops.",
    affiliation: "Faculty of Management and Commerce, RUAS",
    linkedin: "https://www.linkedin.com/in/ajay-r-50b467270",
  },
  {
    id: "kiran-kumar",
    name: "Dr. Kiran Kumar B M",
    role: "Head Event & Campus Coordination (RT Campus)",
    designation: "Associate Professor of FET, RUAS",
    roleGroup: "Executive Council",
    initials: "KK",
    image: "/images/committee/kiran-kumar.webp",
    bio: "Directing multi-campus operations, engineering school collaborations, and technical-to-leadership transition programs.",
    affiliation: "Faculty of Engineering & Technology, RUAS",
    linkedin: "https://www.linkedin.com/in/dr-kiran-kumar-b-m-17539769",
  },
  {
    id: "pallabi-mund",
    name: "Dr. Pallabi Mund",
    role: "Head Event & Campus Coordination (GG Campus)",
    designation: "Associate Professor of FMC, RUAS",
    roleGroup: "Executive Council",
    initials: "PM",
    image: "/images/committee/pallabi-mund.webp",
    bio: "Head of Events and Campus Engagement at Gnanagangothri Campus, leading flagship summit coordination and reporting.",
    affiliation: "Faculty of Management and Commerce, RUAS",
    linkedin: "https://www.linkedin.com/in/dr-pallabi-mund-53163a20",
  },
  {
    id: "sujata-bijwe",
    name: "Ms. Sujata Bijwe",
    role: "Head Industry Connect",
    designation: "Adjunct Faculty of FMC, RUAS",
    roleGroup: "Executive Council",
    initials: "SB",
    image: "/images/committee/sujata-bijwe.webp",
    bio: "Facilitating corporate sponsorships, executive masterclasses, and national leadership board advisory partnerships.",
    affiliation: "Faculty of Management and Commerce, RUAS",
    linkedin: null,
  },
];

export const CORE_LEADERSHIP: BoardMember[] = [
  {
    id: "gurutejas-c",
    name: "Mr. Gurutejas C",
    role: "Sr. President",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Core Committee",
    initials: "GC",
    image: "/images/committee/gurutejas-c.webp",
    bio: "Spearheading overall student leadership, inter-university alliances, and strategic initiative execution.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/gurutejas-c-215216291/",
  },
  {
    id: "abhijit-arya",
    name: "Mr. Abhijit Arya",
    role: "Sr. Vice President",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Core Committee",
    initials: "AA",
    image: "/images/committee/abhijit-arya.webp",
    bio: "Overseeing summit operations, corporate delegacy integration, and national outreach initiatives.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/abhijit-arya-402570285/",
  },
  {
    id: "laksh-soorya-singh",
    name: "Mr. Laksh Soorya Singh",
    role: "Sr. Events & Operations Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Core Committee",
    initials: "LS",
    image: "/images/committee/laksh-soorya-singh.webp",
    bio: "Directing high-stakes event logistics, keynote stage production, and venue management.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/laksh-soorya-singh-ab4212291/",
  },
  {
    id: "bhawen-maroo",
    name: "Mr. Bhawen Maroo",
    role: "Sr. Events & Operations Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Core Committee",
    initials: "BM",
    image: "/images/committee/bhawen-maroo.webp",
    bio: "Managing seamless on-ground event protocol, guest hospitality, and delegate operations.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/bhawen-maroo/",
  },
  {
    id: "shreesha-sn",
    name: "Ms. Shreesha S.N",
    role: "Sr. Social Media & Design Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Core Committee",
    initials: "SS",
    image: "/images/committee/shreesha-sn.webp",
    bio: "Curating digital brand identity, multimedia storytelling, and national outreach campaigns.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/shreesha-s-n-549536292/",
  },
  {
    id: "bharvi-padia",
    name: "Ms. Bharvi A Padia",
    role: "Sr. PR Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Core Committee",
    initials: "BP",
    image: "/images/committee/bharvi-padia.webp",
    bio: "Managing press relations, national media coverage, and dignitary public affairs.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/bharvi-a-7063a62a0/",
  },
  {
    id: "arvind-rakshith",
    name: "Mr. Arvind Rakshith G",
    role: "Sr. Finance & Sponsorship Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Core Committee",
    initials: "AR",
    image: "/images/committee/arvind-rakshith.webp",
    bio: "Structuring corporate sponsorship packages, partner allocations, and financial accounting.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/arvind-rakshith-94a36a375/",
  },
  {
    id: "syed-furqaan",
    name: "Mr. Syed Furqaan Ahmed",
    role: "Sr. Research & Development Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Core Committee",
    initials: "SF",
    image: "/images/committee/syed-furqaan.webp",
    bio: "Authoring capability gap whitepapers, academic research surveys, and impact metrics.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/sydkwests/",
  },
];

export const ORGANIZING_COMMITTEE: BoardMember[] = [
  {
    id: "nuthan-h",
    name: "Nuthan H",
    role: "President",
    designation: "Organizing Committee, LEADS",
    roleGroup: "Organizing Team",
    initials: "NH",
    image: "/images/committee/nuthan-h.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "kunal-bhadauria",
    name: "Kunal Bhadauria",
    role: "Vice President",
    designation: "Organizing Committee, LEADS",
    roleGroup: "Organizing Team",
    initials: "KB",
    image: "/images/committee/kunal-bhadauria.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "kayomarz-pavri",
    name: "Kayomarz Pavri",
    role: "Head - Design & Digital Media",
    designation: "Organizing Committee & Tech Lead",
    roleGroup: "Organizing Team",
    initials: "KP",
    image: "/images/committee/kayomarz-pavri.webp",
    affiliation: "LEADS Next Gen Centre",
  },
  {
    id: "shwetha-s",
    name: "Shwetha S",
    role: "Head - Design and Social Media",
    designation: "Organizing Committee",
    roleGroup: "Organizing Team",
    initials: "SS",
    image: "/images/committee/shwetha-s.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "sudev-mitra",
    name: "Sudev Mitra",
    role: "Chief Coordinator",
    designation: "Organizing Committee",
    roleGroup: "Organizing Team",
    initials: "SM",
    image: "/images/committee/sudev-mitra.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "jyotsna-karn",
    name: "Jyotsna Karn",
    role: "Chief Coordinator",
    designation: "Organizing Committee",
    roleGroup: "Organizing Team",
    initials: "JK",
    image: "/images/committee/jyotsna-karn.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "pranav-pj",
    name: "Pranav P J",
    role: "Chief Coordinator",
    designation: "Organizing Committee",
    roleGroup: "Organizing Team",
    initials: "PP",
    image: "/images/committee/pranav-pj.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "shravya-t",
    name: "Shravya T",
    role: "Chief Coordinator",
    designation: "Organizing Committee",
    roleGroup: "Organizing Team",
    initials: "ST",
    image: "/images/committee/shravya-t.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "shriram-sg",
    name: "Shriram SG",
    role: "General Secretary",
    designation: "Organizing Committee",
    roleGroup: "Organizing Team",
    initials: "SS",
    image: "/images/committee/shriram-sg.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "bhavya-shree",
    name: "S Bhavya Shree",
    role: "General Secretary",
    designation: "Organizing Committee",
    roleGroup: "Organizing Team",
    initials: "BS",
    image: "/images/committee/bhavya-shree.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "manoj-petakamsetty",
    name: "Manoj Petakamsetty",
    role: "General Secretary",
    designation: "Organizing Committee",
    roleGroup: "Organizing Team",
    initials: "MP",
    image: "/images/committee/manoj-petakamsetty.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "yash-chandak",
    name: "Yash Chandak",
    role: "Head - Operations and Logistics",
    designation: "Organizing Committee",
    roleGroup: "Organizing Team",
    initials: "YC",
    image: "/images/committee/yash-chandak.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "niyati-chawra",
    name: "Niyati Chawra",
    role: "Head - Leadership and Development",
    designation: "Organizing Committee",
    roleGroup: "Organizing Team",
    initials: "NC",
    image: "/images/committee/niyati-chawra.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "sadiya-sawood",
    name: "Sadiya Sawood",
    role: "Head - Leadership and Development",
    designation: "Organizing Committee",
    roleGroup: "Organizing Team",
    initials: "SS",
    image: "/images/committee/sadiya-sawood.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "nimisha-km",
    name: "Nimisha K M",
    role: "Head - Sustainability and Innovation",
    designation: "Organizing Committee",
    roleGroup: "Organizing Team",
    initials: "NK",
    image: "/images/committee/nimisha-km.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "kishan-kp",
    name: "Kishan KP",
    role: "Head - Marketing and Branding",
    designation: "Organizing Committee",
    roleGroup: "Organizing Team",
    initials: "KK",
    image: "/images/committee/kishan-kp.webp",
    affiliation: "Organizing Committee",
  },
  {
    id: "aravind-manashetti",
    name: "Aravind Manashetti",
    role: "Head - Finance and Sponsorship",
    designation: "Organizing Committee",
    roleGroup: "Organizing Team",
    initials: "AM",
    image: "/images/committee/arvind-manashetti.webp",
    affiliation: "Organizing Committee",
  },
];

export const GOVERNING_ADVISORS: BoardMember[] = [
  {
    id: "ramanan-ramanathan",
    name: "Mr. Ramanan Ramanathan",
    role: "Governing Advisory Board",
    designation: "Mission Director, Atal Innovation Mission | Chairperson, DST, GoI",
    roleGroup: "Governing & Advisory",
    initials: "RR",
    image: "/images/speakers/ramanan-ramanathan.webp",
    affiliation: "Department of Science & Technology, Govt of India",
    linkedin: "https://www.linkedin.com/in/rramanan27",
  },
  {
    id: "rishikesh-patankar",
    name: "Mr. Rishikesh Patankar",
    role: "Governing Advisory Board",
    designation: "Vice President, National Skill Development Corporation (NSDC)",
    roleGroup: "Governing & Advisory",
    initials: "RP",
    image: "/images/speakers/rishikesh-patankar.webp",
    affiliation: "National Skill Development Corporation",
    linkedin: "https://www.linkedin.com/in/rishikesh-patankar-ph-d-a0bb0863",
  },
  {
    id: "balakrishnan-i",
    name: "Mr. Balakrishnan I",
    role: "Governing Advisory Board",
    designation: "Joint Director / Scientist, Ministry of Electronics & IT, GoI",
    roleGroup: "Governing & Advisory",
    initials: "BI",
    image: "/images/speakers/balakrisnan-i.webp",
    affiliation: "Ministry of Electronics & IT (MeitY)",
    linkedin: "https://www.linkedin.com/in/balakrishna-i-9a4257181",
  },
  {
    id: "anisshh-somani",
    name: "Mr. Anisshh Somani",
    role: "Governing Advisory Board",
    designation: "Program Director, INDIAai, Govt of India",
    roleGroup: "Governing & Advisory",
    initials: "AS",
    image: "/images/speakers/ashish-somani.webp",
    affiliation: "INDIAai, Government of India",
    linkedin: "https://www.linkedin.com/in/anishsomani/",
  },
  {
    id: "vidur-dewan",
    name: "Mr. Vidur Dewan",
    role: "Corporate Advisory Board",
    designation: "Associate VP, Edelman Global Advisory",
    roleGroup: "Governing & Advisory",
    initials: "VD",
    image: "/images/speakers/vidur-dewan.webp",
    affiliation: "Edelman Global Advisory",
    linkedin: "https://www.linkedin.com/in/vidur-d",
  },
  {
    id: "praveen-kamath",
    name: "Dr. Praveen Kamath Kumbla",
    role: "Corporate Advisory Board",
    designation: "General Manager HR, Wipro",
    roleGroup: "Governing & Advisory",
    initials: "PK",
    image: "/images/speakers/praveen-kamath.webp",
    affiliation: "Wipro Global HR",
    linkedin: "https://www.linkedin.com/in/dr-praveen-kamath-kumbla-04111811a",
  },
];

export const BOARD_MEMBERS_DATA: BoardMember[] = [
  ...EXECUTIVE_COUNCIL,
  ...CORE_LEADERSHIP,
  ...ORGANIZING_COMMITTEE,
  ...GOVERNING_ADVISORS,
];
