export interface BoardMember {
  id: string;
  placeholderId?: number;
  name: string;
  role: string;
  designation: string;
  roleGroup:
    | "Centers Leadership"
    | "Alumni Student Council"
    | "Student Core Council"
    | "Student Advisory Council"
    | "Student Trainee Associates"
    | "Core Committee"
    | "Governing & Advisory";
  advisorySubGroup?:
    | "Board of Governing Council"
    | "Corporate Advisory Council"
    | "Academic Advisory Council";
  initials: string;
  image?: string;
  bio?: string;
  message?: string;
  affiliation: string;
  linkedin?: string | null;
}

export const LEADERSHIP_MESSAGES: BoardMember[] = [
  {
    id: "kuldeep-raina",
    placeholderId: 1,
    name: "Prof. Kuldeep Kumar Raina",
    role: "PATRON",
    designation: "Hon. Vice Chancellor, RUAS",
    roleGroup: "Centers Leadership",
    initials: "KR",
    image: "/images/leadership/kuldeep-raina.webp",
    message:
      "Developing futuristic leaders focused on sustainable action. Leadership is responsibility, empathy, and compassion in driving India's socio-economic advancement.",
    bio: "Guiding the academic vision and strategic national direction of LEADS Next Gen Centre as Patron and Vice-Chancellor of MSRUAS.",
    affiliation: "Ramaiah University of Applied Sciences",
    linkedin: "https://www.linkedin.com/in/dr-kuldeep-raina-b4207524",
  },
  {
    id: "sharath-kumar",
    placeholderId: 2,
    name: "Dr. K. M. Sharath Kumar",
    role: "CHIEF ADVISOR",
    designation: "Dean, Faculty of Management and Commerce - RUAS",
    roleGroup: "Centers Leadership",
    initials: "SK",
    image: "/images/leadership/sharath-kumar.webp",
    message:
      "A platform for students, faculty, and industry leaders to tackle contemporary challenges and work towards Viksit Bharat 2047 through non-technical skill upliftment.",
    bio: "Dean of the Faculty of Management and Commerce, overseeing curriculum modernization and institutional industry bridges.",
    affiliation: "Faculty of Management and Commerce, RUAS",
    linkedin: "https://www.linkedin.com/in/dr-k-m-sharath-kumar-ph-d-80400714",
  },
  {
    id: "subhadeep-mukherjee",
    placeholderId: 3,
    name: "Dr. Subhadeep Mukherjee",
    role: "ADVISOR",
    designation: "CEO of Ramaiah Technology Business Incubator",
    roleGroup: "Centers Leadership",
    initials: "SM",
    image: "/images/leadership/subhadeep-mukherjee.webp",
    message:
      "We unite industry leaders and young change-makers to discuss innovative solutions, emphasizing dialogue, collaborative execution, and ethical leadership.",
    bio: "Chief Executive Officer of Ramaiah Technology Business Incubator (RTBI), guiding technology acceleration, strategic incubation, and enterprise innovation.",
    affiliation: "Ramaiah Technology Business Incubator (RTBI) / RUAS",
    linkedin: "https://www.linkedin.com/in/dr-subhadeep-mukherjee-aa78a182",
  },
];

export const EXECUTIVE_COUNCIL: BoardMember[] = [
  ...LEADERSHIP_MESSAGES,
  {
    id: "pallabi-mund",
    placeholderId: 4,
    name: "Dr. Pallabi Mund",
    role: "CENTRE HEAD",
    designation: "Centre Head, LEADS Next-Gen Centre",
    roleGroup: "Centers Leadership",
    initials: "PM",
    image: "/images/committee/pallabi-mund.webp",
    message:
      "Empowering students and faculty to build transformational leadership initiatives across campuses.",
    bio: "Centre Head of LEADS Next Gen Centre & Associate Professor at Faculty of Management and Commerce, directing day-to-day operations, multi-campus student leadership programs, and flagship summits.",
    affiliation: "LEADS Next Gen Centre / Faculty of Management and Commerce, RUAS",
    linkedin: "https://www.linkedin.com/in/dr-pallabi-mund-53163a20",
  },
  {
    id: "sujata-bijwe",
    placeholderId: 6,
    name: "Ms. Sujata Bijwe",
    role: "Head Industry Connect",
    designation: "Adjunct Faculty of Faculty of Management and Commerce, RUAS",
    roleGroup: "Centers Leadership",
    initials: "SB",
    image: "/images/committee/sujata-bijwe.webp",
    bio: "Head of Industry Connect driving 'Real Exposure, Real Readiness' initiatives. Facilitating corporate partnerships, executive roundtables, fireside sessions, and bridging the gap between academic curricula and industry expectations.",
    affiliation: "Faculty of Management and Commerce, RUAS",
    linkedin: null,
  },
  {
    id: "ajay-r",
    placeholderId: 7,
    name: "Dr. Ajay R",
    role: "Finance Advisor & Auditor",
    designation: "Sr. Assistant Professor & Program Head - BCom, Faculty of Management and Commerce, RUAS",
    roleGroup: "Centers Leadership",
    initials: "AR",
    image: "/images/committee/ajay-r.webp",
    bio: "Managing institutional fiscal compliance, budgeting, and financial governance for all LEADS summits and workshops.",
    affiliation: "Faculty of Management and Commerce, RUAS",
    linkedin: "https://www.linkedin.com/in/ajay-r-50b467270",
  },
  {
    id: "kiran-kumar",
    placeholderId: 5,
    name: "Dr. Kiran Kumar B.M.",
    role: "Head Events (RTC Campus)",
    designation: "Associate Professor of FET, RUAS | Head - IIC, RUAS",
    roleGroup: "Centers Leadership",
    initials: "KK",
    image: "/images/committee/kiran-kumar.webp",
    bio: "Directing multi-campus operations, engineering school collaborations, and technical-to-leadership transition programs.",
    affiliation: "Faculty of Engineering & Technology, RUAS",
    linkedin: "https://www.linkedin.com/in/dr-kiran-kumar-b-m-17539769",
  },
  {
    id: "tapas-kumar-sahoo",
    placeholderId: 8,
    name: "Dr. Tapas Kumar Sahoo",
    role: "Finance Officer",
    designation: "Assistant Professor of Faculty of Management and Commerce, RUAS",
    roleGroup: "Centers Leadership",
    initials: "TS",
    image: "/images/committee/tapas-kumar-sahoo.webp",
    bio: "Academician and researcher in Commerce & Management, specializing in corporate finance, financial econometrics, and quantitative research at Faculty of Management and Commerce, RUAS.",
    affiliation: "Faculty of Management and Commerce, RUAS",
    linkedin: null,
  },
];

export const CORE_LEADERSHIP: BoardMember[] = [
  {
    id: "gurutejas-c",
    placeholderId: 8,
    name: "Mr. Gurutejas C",
    role: "Sr. President",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "GC",
    image: "/images/committee/gurutejas-c.webp",
    bio: "Spearheading overall student leadership, inter-university alliances, and strategic initiative execution.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/gurutejas-c-215216291/",
  },
  {
    id: "abhijit-arya",
    placeholderId: 9,
    name: "Mr. Abhijit Arya",
    role: "Sr. Vice President",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "AA",
    image: "/images/committee/abhijit-arya.webp",
    bio: "Overseeing summit operations, corporate delegacy integration, and national outreach initiatives.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/abhijit-arya-402570285/",
  },
  {
    id: "laksh-soorya-singh",
    placeholderId: 10,
    name: "Mr. Laksh Soorya Singh",
    role: "Sr. Events & Operations Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "LS",
    image: "/images/committee/laksh-soorya-singh.webp",
    bio: "Directing high-stakes event logistics, keynote stage production, and venue management.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/laksh-soorya-singh-ab4212291/",
  },
  {
    id: "bhawen-maroo",
    placeholderId: 11,
    name: "Mr. Bhawen Maroo",
    role: "Sr. Events & Operations Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "BM",
    image: "/images/committee/bhawen-maroo.webp",
    bio: "Managing seamless on-ground event protocol, guest hospitality, and delegate operations.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/bhawen-maroo/",
  },
  {
    id: "shreesha-sn",
    placeholderId: 12,
    name: "Ms. Shreesha S.N",
    role: "Sr. Social Media & Design Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "SS",
    image: "/images/committee/shreesha-sn.webp",
    bio: "Curating digital brand identity, multimedia storytelling, and national outreach campaigns.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/shreesha-s-n-549536292/",
  },
  {
    id: "bharvi-padia",
    placeholderId: 13,
    name: "Ms. Bharvi A Padia",
    role: "Sr. PR Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "BP",
    image: "/images/committee/bharvi-padia.webp",
    bio: "Managing press relations, national media coverage, and dignitary public affairs.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/bharvi-a-7063a62a0/",
  },
  {
    id: "arvind-rakshith",
    placeholderId: 14,
    name: "Mr. Arvind Rakshith G",
    role: "Sr. Finance & Sponsorship Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "AR",
    image: "/images/committee/arvind-rakshith.webp",
    bio: "Structuring corporate sponsorship packages, partner allocations, and financial accounting.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/arvind-rakshith-94a36a375/",
  },
  {
    id: "syed-furqaan",
    placeholderId: 15,
    name: "Mr. Syed Furqaan Ahmed",
    role: "Sr. Research & Development Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "SF",
    image: "/images/committee/syed-furqaan.webp",
    bio: "Authoring capability gap whitepapers, academic research surveys, and impact metrics.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: "https://www.linkedin.com/in/sydkwests/",
  },
  {
    id: "sadiya-sawood",
    placeholderId: 29,
    name: "Ms. Sadiya Sawood",
    role: "Sr. Leadership & Development Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "SS",
    image: "/images/committee/sadiya-sawood.webp",
    bio: "Guiding leadership training modules, student executive mentoring, and capability development.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: null,
  },
  {
    id: "nimisha-km",
    placeholderId: 30,
    name: "Ms. Nimisha K M",
    role: "Sr. Sustainability & Innovation Head",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Alumni Student Council",
    initials: "NK",
    image: "/images/committee/nimisha-km.webp",
    bio: "Spearheading sustainability initiatives, environmental leadership, and innovative student tracks.",
    affiliation: "LEADS Next Gen Centre",
    linkedin: null,
  },
];

export const CORE_COMMITTEE: BoardMember[] = [
  {
    id: "nuthan-h",
    placeholderId: 16,
    name: "Nuthan H",
    role: "President",
    designation: "Core Committee, LEADS",
    roleGroup: "Core Committee",
    initials: "NH",
    image: "/images/committee/nuthan-h.webp",
    affiliation: "Core Committee",
  },
  {
    id: "kunal-bhadauria",
    placeholderId: 17,
    name: "Kunal Bhadauria",
    role: "Vice President",
    designation: "Core Committee, LEADS",
    roleGroup: "Core Committee",
    initials: "KB",
    image: "/images/committee/kunal-bhadauria.webp",
    affiliation: "Core Committee",
  },
  {
    id: "kayomarz-pavri",
    placeholderId: 18,
    name: "Kayomarz Pavri",
    role: "Head - Design & Digital Media",
    designation: "Core Committee & Tech Lead",
    roleGroup: "Core Committee",
    initials: "KP",
    image: "/images/committee/kayomarz-pavri.webp",
    affiliation: "LEADS Next Gen Centre",
  },
  {
    id: "shwetha-s",
    placeholderId: 19,
    name: "Shwetha S",
    role: "Head - Design and Social Media",
    designation: "Core Committee",
    roleGroup: "Core Committee",
    initials: "SS",
    image: "/images/committee/shwetha-s.webp",
    affiliation: "Core Committee",
  },
  {
    id: "jyotsna-karn",
    placeholderId: 21,
    name: "Jyotsna Karn",
    role: "Chief Coordinator",
    designation: "Core Committee",
    roleGroup: "Core Committee",
    initials: "JK",
    image: "/images/committee/jyotsna-karn.webp",
    affiliation: "Core Committee",
  },
  {
    id: "pranav-pj",
    placeholderId: 22,
    name: "Pranav P J",
    role: "Chief Coordinator",
    designation: "Core Committee",
    roleGroup: "Core Committee",
    initials: "PP",
    image: "/images/committee/pranav-pj.webp",
    affiliation: "Core Committee",
  },
  {
    id: "shravya-t",
    placeholderId: 23,
    name: "Shravya T",
    role: "Chief Coordinator",
    designation: "Core Committee",
    roleGroup: "Core Committee",
    initials: "ST",
    image: "/images/committee/shravya-t.webp",
    affiliation: "Core Committee",
  },
  {
    id: "p-koushik-reddy",
    placeholderId: 56,
    name: "P Koushik Reddy",
    role: "Chief Coordinator",
    designation: "Core Committee",
    roleGroup: "Core Committee",
    initials: "PK",
    image: "/images/committee/p-koushik-reddy.webp",
    affiliation: "Core Committee",
  },
  {
    id: "shriram-sg",
    placeholderId: 24,
    name: "Shriram SG",
    role: "General Secretary",
    designation: "Core Committee",
    roleGroup: "Core Committee",
    initials: "SS",
    image: "/images/committee/shriram-sg.webp",
    affiliation: "Core Committee",
  },
  {
    id: "manoj-petakamsetty",
    placeholderId: 26,
    name: "Manoj Petakamsetty",
    role: "General Secretary",
    designation: "Core Committee",
    roleGroup: "Core Committee",
    initials: "MP",
    image: "/images/committee/manoj-petakamsetty.webp",
    affiliation: "Core Committee",
  },
  {
    id: "yash-chandak",
    placeholderId: 27,
    name: "Yash Chandak",
    role: "Head - Operations and Logistics",
    designation: "Core Committee",
    roleGroup: "Core Committee",
    initials: "YC",
    image: "/images/committee/yash-chandak.webp",
    affiliation: "Core Committee",
  },
  {
    id: "niyati-chawra",
    placeholderId: 28,
    name: "Niyati Chawra",
    role: "Head - Leadership and Development",
    designation: "Core Committee",
    roleGroup: "Core Committee",
    initials: "NC",
    image: "/images/committee/niyati-chawra.webp",
    affiliation: "Core Committee",
  },
  {
    id: "aravind-manashetti",
    placeholderId: 32,
    name: "Aravind Manashetti",
    role: "Head - Finance and Sponsorship",
    designation: "Core Committee",
    roleGroup: "Core Committee",
    initials: "AM",
    image: "/images/committee/arvind-manashetti.webp",
    affiliation: "Core Committee",
  },
];

export const TRAINEE_ASSOCIATES: BoardMember[] = [
  {
    id: "sudev-mitra",
    placeholderId: 20,
    name: "Sudev Mitra",
    role: "Student Trainee Associate",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Student Trainee Associates",
    initials: "SM",
    image: "/images/committee/sudev-mitra.webp",
    affiliation: "Trainee Associates Wing",
  },
  {
    id: "archana-s-nair",
    placeholderId: 49,
    name: "Archana S Nair",
    role: "Student Trainee Associate",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Student Trainee Associates",
    initials: "AN",
    image: "/images/committee/archana-s-nair.webp",
    affiliation: "Trainee Associates Wing",
  },
  {
    id: "abdul-samad-khatta",
    placeholderId: 50,
    name: "Abdul Samad Khatta",
    role: "Student Trainee Associate",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Student Trainee Associates",
    initials: "AK",
    image: "/images/committee/abdul-samad-khatta.webp",
    affiliation: "Trainee Associates Wing",
  },
  {
    id: "mohammed-ibrahim",
    placeholderId: 51,
    name: "Mohammed Ibrahim",
    role: "Student Trainee Associate",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Student Trainee Associates",
    initials: "MI",
    image: "/images/committee/mohammed-ibrahim.webp",
    affiliation: "Trainee Associates Wing",
  },
  {
    id: "pranav-bansal",
    placeholderId: 52,
    name: "Pranav Bansal",
    role: "Student Trainee Associate",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Student Trainee Associates",
    initials: "PB",
    image: "/images/committee/pranav-bansal.webp",
    affiliation: "Trainee Associates Wing",
  },
  {
    id: "pruthvi-arya-singh",
    placeholderId: 53,
    name: "Pruthvi Arya Singh",
    role: "Student Trainee Associate",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Student Trainee Associates",
    initials: "PS",
    image: "/images/committee/pruthvi-arya-singh.webp",
    affiliation: "Trainee Associates Wing",
  },
  {
    id: "siddharth-gupta",
    placeholderId: 54,
    name: "Siddharth Gupta",
    role: "Student Trainee Associate",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Student Trainee Associates",
    initials: "SG",
    image: "/images/committee/siddharth-gupta.webp",
    affiliation: "Trainee Associates Wing",
  },
  {
    id: "rohit-kumar-raj",
    placeholderId: 55,
    name: "Rohit Kumar Raj",
    role: "Student Trainee Associate",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Student Trainee Associates",
    initials: "RR",
    image: "/images/committee/rohit-kumar-raj.webp",
    affiliation: "Trainee Associates Wing",
  },
  {
    id: "jagannadh-r-krishna",
    placeholderId: 57,
    name: "Jagannadh R Krishna",
    role: "Student Trainee Associate",
    designation: "LEADS Next Gen Centre",
    roleGroup: "Student Trainee Associates",
    initials: "JK",
    image: "/images/committee/jagannadh-r-krishna.webp",
    affiliation: "Trainee Associates Wing",
  },
];

export const ORGANIZING_COMMITTEE = CORE_COMMITTEE;

export const STUDENT_ADVISORY_COUNCIL: BoardMember[] = [
  {
    id: "sahana-mahadev",
    placeholderId: 33,
    name: "Sahana Mahadev",
    role: "Sr. Student Advisor",
    designation: "Student Advisory Council, LEADS",
    roleGroup: "Student Advisory Council",
    initials: "SM",
    image: "/images/committee/sahana-mahadev.webp",
    affiliation: "LEADS Student Advisory Council",
  },
  {
    id: "anurag-pandey",
    placeholderId: 34,
    name: "Anurag Pandey",
    role: "Sr. Student Advisor",
    designation: "Student Advisory Council, LEADS",
    roleGroup: "Student Advisory Council",
    initials: "AP",
    image: "/images/committee/anurag-pandey.webp",
    affiliation: "LEADS Student Advisory Council",
  },
];

export const GOVERNING_ADVISORS: BoardMember[] = [
  // 1. BOARD OF GOVERNING COUNCIL
  {
    id: "rishikesh-patankar",
    placeholderId: 36,
    name: "Dr. Rishikesh Patankar",
    role: "Governing Council",
    designation: "Vice President, National Skill Development Corporation",
    roleGroup: "Governing & Advisory",
    advisorySubGroup: "Board of Governing Council",
    initials: "RP",
    image: "/images/advisors/rishikesh-patankar.webp",
    affiliation: "National Skill Development Corporation (NSDC)",
    linkedin: "https://www.linkedin.com/in/rishikesh-patankar-ph-d-a0bb0863",
  },
  {
    id: "ramanan-ramanathan",
    placeholderId: 35,
    name: "Dr. Ramanan Ramanathan",
    role: "Governing Council",
    designation: "Chairperson, Dept. of Science & Technology GoI & Founder Mission Director, AIM",
    roleGroup: "Governing & Advisory",
    advisorySubGroup: "Board of Governing Council",
    initials: "RR",
    image: "/images/advisors/ramanan-ramanathan.webp",
    affiliation: "Department of Science & Technology, Govt of India",
    linkedin: "https://www.linkedin.com/in/rramanan27",
  },
  {
    id: "balakrishnan-i",
    placeholderId: 37,
    name: "Mr. Balakrisnan . I",
    role: "Governing Council",
    designation: "Joint Director / Scientist, Ministry of Electronics & Information Technology, GoI",
    roleGroup: "Governing & Advisory",
    advisorySubGroup: "Board of Governing Council",
    initials: "BI",
    image: "/images/speakers/balakrisnan-i.webp",
    affiliation: "Ministry of Electronics & Information Technology, Government of India",
    linkedin: "https://www.linkedin.com/in/balakrishna-i-9a4257181",
  },
  {
    id: "aman-bhaiya",
    placeholderId: 41,
    name: "Mr. Aman Bhaiya",
    role: "Governing Council",
    designation: "Vice President, SBI Foundation",
    roleGroup: "Governing & Advisory",
    advisorySubGroup: "Board of Governing Council",
    initials: "AB",
    image: "/images/advisors/aman-bhaiya.webp",
    affiliation: "SBI Foundation",
    linkedin: "https://www.linkedin.com/in/amanbhaiya",
  },
  {
    id: "apurva-mishra",
    placeholderId: 44,
    name: "Mr. Apurva Kumar Mishra",
    role: "Governing Council",
    designation: "Consultant, Economic Advisory Board, Prime Minister of India",
    roleGroup: "Governing & Advisory",
    advisorySubGroup: "Board of Governing Council",
    initials: "AM",
    image: "/images/speakers/apurva-mishra.webp",
    affiliation: "Economic Advisory Board, Prime Minister of India",
    linkedin: "https://www.linkedin.com/in/apurvakumarmishra/",
  },
  {
    id: "anish-somani",
    placeholderId: 38,
    name: "Mr. Ashish Somani",
    role: "Governing Council",
    designation: "Program Director, Ministry of Electronics & IT & INDIAai, Government of India",
    roleGroup: "Governing & Advisory",
    advisorySubGroup: "Board of Governing Council",
    initials: "AS",
    image: "/images/speakers/ashish-somani.webp",
    affiliation: "MeitY & INDIAai, Government of India",
    linkedin: "https://www.linkedin.com/in/anishsomani/",
  },

  // 2. CORPORATE ADVISORY COUNCIL
  {
    id: "vidur-dewan",
    placeholderId: 39,
    name: "Mr. Vidur Dewan",
    role: "Corporate Advisory Council",
    designation: "Associate Vice President, Edelman Global Advisory & Former Associate PMO",
    roleGroup: "Governing & Advisory",
    advisorySubGroup: "Corporate Advisory Council",
    initials: "VD",
    image: "/images/advisors/vidur-dewan.webp",
    affiliation: "Edelman Global Advisory",
    linkedin: "https://www.linkedin.com/in/vidur-d",
  },
  {
    id: "ganesaraman-k",
    placeholderId: 42,
    name: "Dr. Ganesaraman K",
    role: "Corporate Advisory Council",
    designation: "Vice President and Head of Global Internal Audit at [24]7.ai & CSR Trustee",
    roleGroup: "Governing & Advisory",
    advisorySubGroup: "Corporate Advisory Council",
    initials: "GK",
    image: "/images/advisors/ganesaraman-k.webp",
    affiliation: "[24]7.ai",
    linkedin: "https://www.linkedin.com/in/ganesaraman",
  },
  {
    id: "praveen-kamath",
    placeholderId: 40,
    name: "Dr. Praveen Kamath Kumbla",
    role: "Corporate Advisory Council",
    designation: "General Manager HR, Global Strategic Hiring & Redeployment Head, Wipro",
    roleGroup: "Governing & Advisory",
    advisorySubGroup: "Corporate Advisory Council",
    initials: "PK",
    image: "/images/speakers/praveen-kamath.webp",
    affiliation: "Wipro Global HR",
    linkedin: "https://www.linkedin.com/in/dr-praveen-kamath-kumbla-04111811a",
  },
  {
    id: "vithal-madyalkar",
    placeholderId: 46,
    name: "Mr. Vithal Madyalkar",
    role: "Corporate Advisory Council",
    designation: "Director, IBM Innovation Centre for Education",
    roleGroup: "Governing & Advisory",
    advisorySubGroup: "Corporate Advisory Council",
    initials: "VM",
    image: "/images/speakers/vithal-madyalkar.webp",
    affiliation: "IBM Innovation Centre for Education",
    linkedin: "https://www.linkedin.com/in/vithalm",
  },
  {
    id: "manoj-prasad",
    placeholderId: 43,
    name: "Mr. Manoj Prasad",
    role: "Corporate Advisory Council",
    designation: "Regional Head, Tata Capital",
    roleGroup: "Governing & Advisory",
    advisorySubGroup: "Corporate Advisory Council",
    initials: "MP",
    image: "/images/advisors/manoj-prasad.webp",
    affiliation: "Tata Capital",
    linkedin: "https://www.linkedin.com/in/prasadmanoj",
  },

  // 3. ACADEMIC ADVISORY COUNCIL
  {
    id: "govind-kadambi",
    placeholderId: 49,
    name: "Prof. Govind R. Kadambi",
    role: "Academic Advisory Council",
    designation: "Professor, Ramaiah University of Applied Sciences",
    roleGroup: "Governing & Advisory",
    advisorySubGroup: "Academic Advisory Council",
    initials: "GK",
    image: "/images/advisors/govind-kadambi.webp",
    affiliation: "Ramaiah University of Applied Sciences",
    linkedin: null,
  },
  {
    id: "bala-subrahmanya",
    placeholderId: 48,
    name: "Dr. M.H. Bala Subramanya",
    role: "Academic Advisory Council",
    designation: "Professor, Department of Management Studies, Indian Institute of Science, Bangalore",
    roleGroup: "Governing & Advisory",
    advisorySubGroup: "Academic Advisory Council",
    initials: "BS",
    image: "/images/advisors/bala-subrahmanya.webp",
    affiliation: "Indian Institute of Science (IISc), Bangalore",
    linkedin: "https://www.linkedin.com/in/bala-subrahmanya-m-h-680b968/",
  },
  {
    id: "jon-thomas",
    placeholderId: 47,
    name: "Dr. Jon Thomas",
    role: "Academic Advisory Council",
    designation: "Associate Professor, University of Fraser Valley, Canada",
    roleGroup: "Governing & Advisory",
    advisorySubGroup: "Academic Advisory Council",
    initials: "JT",
    image: "/images/speakers/jon-thomas.webp",
    affiliation: "University of Fraser Valley, Canada",
    linkedin: "https://www.linkedin.com/in/drvjthomas",
  },
  {
    id: "suchit-ahuja",
    placeholderId: 45,
    name: "Dr. Suchit Ahuja",
    role: "Academic Advisory Council",
    designation: "Associate Professor Business Technology Management, Concordia University, Canada, USA",
    roleGroup: "Governing & Advisory",
    advisorySubGroup: "Academic Advisory Council",
    initials: "SA",
    image: "/images/advisors/suchit-ahuja.webp",
    affiliation: "Concordia University, John Molson School of Business, Canada, USA",
    linkedin: "https://www.linkedin.com/in/asuchit",
  },
];

export const BOARD_MEMBERS_DATA: BoardMember[] = [
  ...EXECUTIVE_COUNCIL,
  ...CORE_LEADERSHIP,
  ...STUDENT_ADVISORY_COUNCIL,
  ...CORE_COMMITTEE,
  ...TRAINEE_ASSOCIATES,
  ...GOVERNING_ADVISORS,
];
